### ISSUE TITLE
Crush in SLIME with SBCL

### ISSUE THREAD

**Issue by komi1230** [3b/cl-opengl#85]
When I make some program using CL-OpenGL, this program doesn't work in SLIME.

Source code looks be compiled, but the window doesn't open.

According to [this page](https://stackoverflow.com/questions/18345464/cl-opengl-under-slime-on-macos-crashing-sbcl-bug), adding `(setf swank:*communication-style* :fd-handler)` to `swank.lisp` may work. 

I tried this, but does't work.

Is this SLIME bug ?

Thank you for your reading this issue :)

**Comment by 3b** [comment]
What OS, and do you get any error messages? (either slime debugger, or messages in *inferior-lisp* buffer)
Does it work if you run it without slime?

On MS Windows, you might need to manually tell it to show the first window you create an extra time due to some oddness in windows APIs. (with cl-glut, call `(glut:show-window)` after running the program, other libraries should have something similar)

On OSX, you need to create all windows in the initial thread, which is what the `:fd-handler` setting is trying to do. Another option is to run the program from the `*inferior-lisp*` buffer.

**Comment by komi1230** [comment]
My environment is macOS Catalina.

My environment about SLIME is like this

```
~/.emacs.d
├── init.el 
└── slime
    ├── swank.lisp
    └── src/
```

I set `(setf swank:*communication-style* :fd-handler)` in this `~/.emacs.d/slime/swank.lisp`.

And when I open SLIME and load `(ql:quickload :cl-opengl)`, SLIME crushes.

Do you have any advice ?

**Comment by komi1230** [comment]
Finally I enabled SLIME to use OpenGL !

In `(defstruct (connection ....)` in `swank.lisp`, I set `(communication-style :fd-handler :type (member nil :spawn :sigio :fd-handler)`.

And in `(defun before-init (...` in the bottom of `swank.lisp`, I set `(setq *communication-style* nil)`.

Then, CL-OpenGL works in SLIME.

Thank you for your checking !
